### ISSUE TITLE
Running the example does not find a plan

### ISSUE THREAD

**Issue by dan-blank** [circuithub/fast-downward#11]
When I run `FastDownward/Examples/Gripper.hs`, I get `Couldn't find a plan!` which is unexpected to me since in https://blog.ocharles.org.uk/posts/2018-12-25-fast-downward.html a plan is found. `downward` is on my PATH.

Using WSL2 on Windows 11.

### Steps:

1. `$ mkdir proj`
2. `$ cd proj`
3. `$ cabal init -p proj`
4. Add fast-doward in proj.cabal:
`    build-depends:    
        base ^>=4.12.0.0,
        fast-downward >= 0.2.2.0`
5. Replace `app/Main.hs` with the content of `FastDownward/Examples/Gripper.hs` from this repo, replacing the module line with `module Main where`
6. `$ cabal run`

**Edit:** Printing the result told me that there seems to be input error: `Couldn't find a plan!InputError`

Assuming that solving the example problem should give a plan, how would I go about debugging this issue?

**Comment by Reasonable-Solutions** [comment]
since i just had to pick up an old thing of mine and ran into the same thing, there's some breakage in how the options are handled in newer versions of fd, i tried a few versions back and at least the 2019 version of fd works fine.

**Comment by dan-blank** [comment]
sorry for the late answer! Glad to hear :)

**Comment by dan-blank** [comment]
Closing this issue: Not tried out the suggested solution, but I am fairly sure it works.
