### ISSUE TITLE
bjolp not exported?

### ISSUE THREAD

**Issue by rberenguel** [circuithub/fast-downward#7]
It may be my Haskell inexperience, but if I want to run `example.hs` as code outside the package, bjolp can't be used (not exported): https://github.com/circuithub/fast-downward/blob/master/FastDownward/Examples/Gripper.hs#L84

It's unclear then how to create a solver: you can't create a "bjolp of your own" either since there are other instances not exported, and needed to create it. 

The previous minor version example works fine though, so this is not stopping me from playing with the library, but you may want to check if it's really a problem or is just me.

Thanks!

**Comment by ocharles** [comment]
Hi, thanks for testing. I think this is now fixed - https://hackage.haskell.org/package/fast-downward-0.2.0.0/docs/FastDownward-Exec.html#v:bjolp
